apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 512Mi # Ajusta la cantidad de almacenamiento según tus necesidades
  accessModes:
    - ReadWriteOnce # o ReadWriteMany si lo necesitas (con cuidado)
  persistentVolumeReclaimPolicy: Retain # o Delete
  # Configuración específica del proveedor de almacenamiento (ejemplo para hostPath)
  hostPath:
    path: /data/postgres # Ruta en el nodo donde se almacenarán los datos
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce # o ReadWriteMany si lo necesitas (con cuidado)
  resources:
    requests:
      storage: 512Mi # Debe coincidir con el PV
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest # Puedes especificar una versión diferente si lo deseas
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres # Usuario por defecto
        - name: POSTGRES_PASSWORD
          value: postgres # Contraseña por defecto
        - name: POSTGRES_DB
          value: basededatos # Nombre de la base de datos por defecto
        volumeMounts: # Para persistir los datos
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim: # Usa un PersistentVolumeClaim si lo deseas
          claimName: postgres-pvc # Debe coincidir con el PVC