apiVersion: v1
kind: Service
metadata:
  name: music-player-service
  namespace: default
spec:
  selector:
    app: music-player
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
